# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friended', to='login_app.User'),
        ),
    ]
